version: 0.0
os: linux
files:
  - source: /
    destination: /webapp/
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/validateService.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/applicationStop.sh
      timeout: 300
      runas: root
