version: 0.0
os: linux
files:
  - source: /home/**/*
    destination: /webapp/
  - source: /main/**/*
    destination: /webapp/
  - source: /static/**/*
    destination: /webapp/
  - source: /templates/**/*
    destination: /webapp/
  - source: /db.sqlite3
    destination: /webapp/
  - source: /manage.py
    destination: /webapp/
  - source: /appspec.yml
    destination: /webapp/
  - source: /scripts/**/*
    destination: /webapp/
  - source: .venv/
    destination: /webapp/.venv/
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 30
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 120
      runas: root
  ValidateService:
    - location: scripts/validateService.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/applicationStop.sh
      timeout: 300
      runas: root
