name: test

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        
 
    - name: AWS credentials
      uses: aws-action/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2


    - name: CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1.0.3
      with:
        project-name: Github-build
